#!/bin/bash
export KITWB_BASH_UTIL_DIR=$KITWB_BASH_DIR/util
export KITWB_BASH_COMMAND_DIR=$KITWB_BASH_DIR/commands
export KITWB_BASH_FUNCTION_DIR=$KITWB_BASH_DIR/functions
export KITWB_SCRIPTS_DIR=$KITWB_BASH_DIR/scripts
export KITWB_TEMPLATES_DIR=$KITWB_BASH_DIR/templates
export KITWB_FILES_DIR=$KITWB_BASH_DIR/files

export KITWB_BASE_DIR=$(pathof $KITWB_BASH_DIR/..)
