
# check to see if /c is there, if it is, then try to mount it to /c on WSL
# if this fails
# https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
export DOCKER_HOST=tcp://0.0.0.0:2375
if [ ! -d "/c" ]; then
	sudo mkdir /c
fi
if [ -d "/c" ]; then
	if ( ! sudo mount --bind /mnt/c /c ) then
		printf "\033[0;31mWARNING: please run kd setup\033[0m\n"
	fi
fi

. ${DEVOPS_DIR}/bash/activate.sh
