site_name: KISIA CLI
site_dir: mkdocs-site
docs_dir: mkdocs-src
nav:
  - Home: 'index.md'
  - CLI: 'tool-manual.md'
  - Dev:
    - KBash: 'kbash-manual.md'
    - 'How do I': 'how-do-i.md'
  - API: 'sphinx/index.html'
