site_name: KIT-Workbench
site_dir: ./mkdocs
docs_dir: ./mkdocs-src
nav:
  - Overview: 'site-notes/overview.md'
  - Platforms: 'site-notes/platforms.md'
  - Notebooks: 'site-notes/notebooks.md'
  - Technical: 'site-notes/technical.md'


